import { AbilityDef } from '../types';

export const ABILITIES: Record<string, AbilityDef> = {
  // KINGDOM PALADIN
  paladin_holy_strike: {
    id: 'paladin_holy_strike',
    name: 'Holy Strike',
    description: 'Strikes an enemy with sacred wrath, dealing 70 damage and stunning for 1.5s.',
    cooldown: 8,
    range: 50,
    targetType: 'target_enemy',
    hotkey: 'Q',
    unlockLevel: 1,
  },
  paladin_heal: {
    id: 'paladin_heal',
    name: 'Holy Light',
    description: 'Channels divine power, healing an allied unit or hero for 140 HP.',
    cooldown: 9,
    range: 160,
    targetType: 'target_ally',
    hotkey: 'W',
    unlockLevel: 1,
  },
  paladin_rally: {
    id: 'paladin_rally',
    name: 'Righteous Rally',
    description: 'Blows a war horn, granting +20% attack damage and +2 armor to nearby allies for 8s.',
    cooldown: 15,
    range: 0,
    radius: 180,
    targetType: 'instant',
    hotkey: 'E',
    unlockLevel: 2,
  },
  paladin_divine_shield: {
    id: 'paladin_divine_shield',
    name: 'Divine Shield',
    description: 'Envelops the Paladin in an impervious holy bubble, preventing all damage for 6s.',
    cooldown: 35,
    range: 0,
    targetType: 'instant',
    hotkey: 'R',
    unlockLevel: 4,
    isUltimate: true,
  },

  // HORDE BLADEMASTER
  blademaster_wind_walk: {
    id: 'blademaster_wind_walk',
    name: 'Wind Walk',
    description: 'Harnesses wind currents, granting +50% move speed and +30 bonus damage on the next attack.',
    cooldown: 10,
    range: 0,
    targetType: 'instant',
    hotkey: 'Q',
    unlockLevel: 1,
  },
  blademaster_whirlwind: {
    id: 'blademaster_whirlwind',
    name: 'Whirlwind',
    description: 'Performs a sweeping 360-degree slash, dealing 75 damage to all nearby enemies.',
    cooldown: 8,
    range: 0,
    radius: 70,
    targetType: 'instant',
    hotkey: 'W',
    unlockLevel: 1,
  },
  blademaster_mirror_image: {
    id: 'blademaster_mirror_image',
    name: 'Mirror Image',
    description: 'Creates a spectral clone that distracts foes and mimics attacks for 15s.',
    cooldown: 16,
    range: 0,
    targetType: 'instant',
    hotkey: 'E',
    unlockLevel: 2,
  },
  blademaster_bladestorm: {
    id: 'blademaster_bladestorm',
    name: 'Bladestorm',
    description: 'Becomes an unstoppable vortex of steel, dealing 80 damage every second to all nearby enemies for 4s.',
    cooldown: 40,
    range: 0,
    radius: 90,
    targetType: 'instant',
    hotkey: 'R',
    unlockLevel: 4,
    isUltimate: true,
  },

  // UNDEAD DEATH KNIGHT
  death_knight_death_coil: {
    id: 'death_knight_death_coil',
    name: 'Death Coil',
    description: 'Fires a concentrated ball of necromantic energy: deals 75 damage to an enemy or heals an undead ally for 130 HP.',
    cooldown: 8,
    range: 160,
    targetType: 'target_enemy',
    hotkey: 'Q',
    unlockLevel: 1,
  },
  death_knight_raise_dead: {
    id: 'death_knight_raise_dead',
    name: 'Raise Dead',
    description: 'Raises up to 2 temporary Skeleton Warriors from nearby corpses to fight for 25s.',
    cooldown: 12,
    range: 180,
    targetType: 'corpse',
    hotkey: 'W',
    unlockLevel: 1,
  },
  death_knight_death_aura: {
    id: 'death_knight_death_aura',
    name: 'Unholy Pulse',
    description: 'Emits a chilling wave, dealing 40 damage and slowing enemy attack and movement speed by 25% for 6s.',
    cooldown: 14,
    range: 0,
    radius: 170,
    targetType: 'instant',
    hotkey: 'E',
    unlockLevel: 2,
  },
  death_knight_army_of_the_dead: {
    id: 'death_knight_army_of_the_dead',
    name: 'Army of the Dead',
    description: 'Summons 4 frenzied undead ghouls from the netherworld to overwhelm foes for 20s.',
    cooldown: 45,
    range: 0,
    targetType: 'instant',
    hotkey: 'R',
    unlockLevel: 4,
    isUltimate: true,
  },

  // ELVES ARCHDRUID
  archdruid_entangle: {
    id: 'archdruid_entangle',
    name: 'Entangle',
    description: 'Roots an enemy target with thorny vines for 4s, preventing movement and dealing 50 damage.',
    cooldown: 9,
    range: 170,
    targetType: 'target_enemy',
    hotkey: 'Q',
    unlockLevel: 1,
  },
  archdruid_moonfall: {
    id: 'archdruid_moonfall',
    name: 'Moonfall',
    description: 'Calls down searing lunar beams, dealing 90 damage in a targeted area.',
    cooldown: 10,
    range: 180,
    radius: 60,
    targetType: 'target_ground',
    hotkey: 'W',
    unlockLevel: 1,
  },
  archdruid_natures_blessing: {
    id: 'archdruid_natures_blessing',
    name: "Nature's Blessing",
    description: 'Surrounds nearby allies with rejuvenating spores, healing 80 HP immediately and 5 HP/sec for 6s.',
    cooldown: 14,
    range: 0,
    radius: 180,
    targetType: 'instant',
    hotkey: 'E',
    unlockLevel: 2,
  },
  archdruid_wrath_of_nature: {
    id: 'archdruid_wrath_of_nature',
    name: 'Wrath of Nature',
    description: 'Awakens an Ancient Treant companion to fight by your side for 30s.',
    cooldown: 45,
    range: 0,
    targetType: 'instant',
    hotkey: 'R',
    unlockLevel: 4,
    isUltimate: true,
  },

  // CASTER UNIT ABILITIES
  battlemage_fireball: {
    id: 'battlemage_fireball',
    name: 'Flame Blast',
    description: 'Hurls a fiery sphere dealing 45 damage in a small radius.',
    cooldown: 7,
    range: 160,
    radius: 40,
    targetType: 'target_enemy',
    hotkey: 'F',
    unlockLevel: 1,
  },
  priest_heal: {
    id: 'priest_heal',
    name: 'Mend',
    description: 'Heals a damaged wounded ally for 50 HP.',
    cooldown: 5,
    range: 150,
    targetType: 'target_ally',
    hotkey: 'H',
    unlockLevel: 1,
  },
  shaman_bloodsurge: {
    id: 'shaman_bloodsurge',
    name: 'Bloodsurge',
    description: 'Infuses an ally with primal energy, increasing attack speed by 30% for 8s.',
    cooldown: 8,
    range: 140,
    targetType: 'target_ally',
    hotkey: 'B',
    unlockLevel: 1,
  },
  necromancer_raise_skeleton: {
    id: 'necromancer_raise_skeleton',
    name: 'Raise Skeleton',
    description: 'Transforms a fallen corpse into a skeleton warrior for 25s.',
    cooldown: 8,
    range: 160,
    targetType: 'corpse',
    hotkey: 'R',
    unlockLevel: 1,
  },
  sorceress_frost_bolt: {
    id: 'sorceress_frost_bolt',
    name: 'Frost Bolt',
    description: 'Chills an enemy, dealing 30 damage and reducing movement speed by 40% for 4s.',
    cooldown: 6,
    range: 160,
    targetType: 'target_enemy',
    hotkey: 'F',
    unlockLevel: 1,
  },
};
