import { BuildingDef } from '../types';

export const BUILDINGS: Record<string, BuildingDef> = {
  // ================= KINGDOMS =================
  kingdoms_main_hall: {
    id: 'kingdoms_main_hall',
    name: 'Main Hall',
    faction: 'kingdoms',
    category: 'main_hall',
    tier: 1,
    hp: 2000,
    goldCost: 350,
    buildTime: 30,
    width: 90,
    height: 90,
    description: 'Central citadel. Deposits gold, trains Peasants, and authorizes higher tech tiers.',
    producesUnits: ['kingdoms_peasant'],
  },
  kingdoms_barracks: {
    id: 'kingdoms_barracks',
    name: 'Barracks',
    faction: 'kingdoms',
    category: 'barracks',
    tier: 1,
    hp: 1100,
    goldCost: 160,
    buildTime: 20,
    width: 80,
    height: 80,
    description: 'Drills frontline swordsmen and armored knights. Researches military upgrades.',
    producesUnits: ['kingdoms_swordsman', 'kingdoms_knight'],
    researchesUpgrades: [
      'weapons_1', 'weapons_2',
      'armor_1', 'armor_2',
      'training_1', 'training_2',
    ],
  },
  kingdoms_archery_range: {
    id: 'kingdoms_archery_range',
    name: 'Archery Range',
    faction: 'kingdoms',
    category: 'ranged',
    tier: 1,
    hp: 950,
    goldCost: 150,
    buildTime: 18,
    width: 75,
    height: 75,
    description: 'Equips longbow archers and constructs siege cannons.',
    producesUnits: ['kingdoms_archer', 'kingdoms_cannon'],
  },
  kingdoms_mage_tower: {
    id: 'kingdoms_mage_tower',
    name: 'Mage Tower',
    faction: 'kingdoms',
    category: 'magic',
    tier: 2,
    hp: 900,
    goldCost: 175,
    buildTime: 22,
    width: 70,
    height: 70,
    description: 'Academy of arcane mysteries. Trains Battlemages and Priests.',
    producesUnits: ['kingdoms_battlemage', 'kingdoms_priest'],
  },
  kingdoms_cathedral: {
    id: 'kingdoms_cathedral',
    name: 'Cathedral',
    faction: 'kingdoms',
    category: 'hero',
    tier: 2,
    hp: 1200,
    goldCost: 200,
    buildTime: 25,
    width: 85,
    height: 85,
    description: 'Sanctified bastion that summons the Paladin Hero and elite Royal Guards.',
    producesUnits: ['kingdoms_paladin', 'kingdoms_royal_guard'],
  },
  kingdoms_guard_tower: {
    id: 'kingdoms_guard_tower',
    name: 'Guard Tower',
    faction: 'kingdoms',
    category: 'tower',
    tier: 1,
    hp: 850,
    goldCost: 120,
    buildTime: 18,
    width: 60,
    height: 60,
    description: 'Fortified stone outpost firing piercing bolts at trespassing enemies.',
    canAttack: true,
    attackDamage: 28,
    attackRange: 180,
    attackSpeed: 1.2,
  },

  // ================= HORDE =================
  horde_main_hall: {
    id: 'horde_main_hall',
    name: 'Great Hall',
    faction: 'horde',
    category: 'main_hall',
    tier: 1,
    hp: 2000,
    goldCost: 350,
    buildTime: 30,
    width: 90,
    height: 90,
    description: 'Clan stronghold. Stores gold, trains Peons, and advances the war effort.',
    producesUnits: ['horde_peon'],
  },
  horde_barracks: {
    id: 'horde_barracks',
    name: 'War Camp',
    faction: 'horde',
    category: 'barracks',
    tier: 1,
    hp: 1100,
    goldCost: 160,
    buildTime: 20,
    width: 80,
    height: 80,
    description: 'Musters fierce Grunts and hulking Ogres.',
    producesUnits: ['horde_grunt', 'horde_ogre'],
    researchesUpgrades: [
      'weapons_1', 'weapons_2',
      'armor_1', 'armor_2',
      'training_1', 'training_2',
    ],
  },
  horde_ranged: {
    id: 'horde_ranged',
    name: 'Troll Hut',
    faction: 'horde',
    category: 'ranged',
    tier: 1,
    hp: 950,
    goldCost: 150,
    buildTime: 18,
    width: 75,
    height: 75,
    description: 'Encourages Troll spear hunters and manufactures war catapults.',
    producesUnits: ['horde_troll_hunter', 'horde_catapult'],
  },
  horde_magic: {
    id: 'horde_magic',
    name: 'Spirit Lodge',
    faction: 'horde',
    category: 'magic',
    tier: 2,
    hp: 900,
    goldCost: 175,
    buildTime: 22,
    width: 70,
    height: 70,
    description: 'Primal totem circle training Spirit Shamans and swift Wolf Riders.',
    producesUnits: ['horde_spirit_shaman', 'horde_wolf_rider'],
  },
  horde_hero: {
    id: 'horde_hero',
    name: 'Warchief Hall',
    faction: 'horde',
    category: 'hero',
    tier: 2,
    hp: 1200,
    goldCost: 200,
    buildTime: 25,
    width: 85,
    height: 85,
    description: 'Summons the feared Blademaster and trains deadly Berserkers.',
    producesUnits: ['horde_blademaster', 'horde_berserker'],
  },
  horde_tower: {
    id: 'horde_tower',
    name: 'Watchtower',
    faction: 'horde',
    category: 'tower',
    tier: 1,
    hp: 850,
    goldCost: 120,
    buildTime: 18,
    width: 60,
    height: 60,
    description: 'Timber and spike sentry tower launching burning spears at intruders.',
    canAttack: true,
    attackDamage: 29,
    attackRange: 175,
    attackSpeed: 1.2,
  },

  // ================= UNDEAD =================
  undead_main_hall: {
    id: 'undead_main_hall',
    name: 'Necropolis',
    faction: 'undead',
    category: 'main_hall',
    tier: 1,
    hp: 2000,
    goldCost: 350,
    buildTime: 30,
    width: 90,
    height: 90,
    description: 'Dark heart of the Scourge. Summons Acolytes and unlocks necromantic tiers.',
    producesUnits: ['undead_acolyte'],
  },
  undead_barracks: {
    id: 'undead_barracks',
    name: 'Crypt',
    faction: 'undead',
    category: 'barracks',
    tier: 1,
    hp: 1100,
    goldCost: 160,
    buildTime: 20,
    width: 80,
    height: 80,
    description: 'Exhumes ravenous Ghouls and stitched Abominations.',
    producesUnits: ['undead_ghoul', 'undead_abomination'],
    researchesUpgrades: [
      'weapons_1', 'weapons_2',
      'armor_1', 'armor_2',
      'training_1', 'training_2',
    ],
  },
  undead_ranged: {
    id: 'undead_ranged',
    name: 'Bone Pit',
    faction: 'undead',
    category: 'ranged',
    tier: 1,
    hp: 950,
    goldCost: 150,
    buildTime: 18,
    width: 75,
    height: 75,
    description: 'Assembles Crypt Archers and heavy Bone Catapults.',
    producesUnits: ['undead_crypt_archer', 'undead_bone_catapult'],
  },
  undead_magic: {
    id: 'undead_magic',
    name: 'Necromancer Sanctum',
    faction: 'undead',
    category: 'magic',
    tier: 2,
    hp: 900,
    goldCost: 175,
    buildTime: 22,
    width: 70,
    height: 70,
    description: 'Dark laboratory instructing Necromancers and conjuring Wraiths.',
    producesUnits: ['undead_necromancer', 'undead_wraith'],
  },
  undead_hero: {
    id: 'undead_hero',
    name: 'Death Shrine',
    faction: 'undead',
    category: 'hero',
    tier: 2,
    hp: 1200,
    goldCost: 200,
    buildTime: 25,
    width: 85,
    height: 85,
    description: 'Resurrects the Death Knight and raises mighty Bone Dragons.',
    producesUnits: ['undead_death_knight', 'undead_bone_dragon'],
  },
  undead_tower: {
    id: 'undead_tower',
    name: 'Bone Tower',
    faction: 'undead',
    category: 'tower',
    tier: 1,
    hp: 850,
    goldCost: 120,
    buildTime: 18,
    width: 60,
    height: 60,
    description: 'Gargoyle spire hurling spectral necromantic bolts.',
    canAttack: true,
    attackDamage: 28,
    attackRange: 180,
    attackSpeed: 1.2,
  },

  // ================= ELVES =================
  elves_main_hall: {
    id: 'elves_main_hall',
    name: 'Tree of Life',
    faction: 'elves',
    category: 'main_hall',
    tier: 1,
    hp: 2000,
    goldCost: 350,
    buildTime: 30,
    width: 90,
    height: 90,
    description: 'Ancient sacred tree. Nurtures Wisps and guides elven evolution.',
    producesUnits: ['elves_wisp'],
  },
  elves_barracks: {
    id: 'elves_barracks',
    name: 'Warrior Grove',
    faction: 'elves',
    category: 'barracks',
    tier: 1,
    hp: 1100,
    goldCost: 160,
    buildTime: 20,
    width: 80,
    height: 80,
    description: 'Trains agile Bladedancers and awakens sturdy Treants.',
    producesUnits: ['elves_bladedancer', 'elves_treant'],
    researchesUpgrades: [
      'weapons_1', 'weapons_2',
      'armor_1', 'armor_2',
      'training_1', 'training_2',
    ],
  },
  elves_ranged: {
    id: 'elves_ranged',
    name: 'Archer Grove',
    faction: 'elves',
    category: 'ranged',
    tier: 1,
    hp: 950,
    goldCost: 150,
    buildTime: 18,
    width: 75,
    height: 75,
    description: 'Fashions longbows for Elven Archers and constructs Nature Catapults.',
    producesUnits: ['elves_archer', 'elves_nature_catapult'],
  },
  elves_magic: {
    id: 'elves_magic',
    name: 'Arcane Grove',
    faction: 'elves',
    category: 'magic',
    tier: 2,
    hp: 900,
    goldCost: 175,
    buildTime: 22,
    width: 70,
    height: 70,
    description: 'Communes with mystic leylines to train Sorceresses and Hippogriff Riders.',
    producesUnits: ['elves_sorceress', 'elves_hippogriff_rider'],
  },
  elves_hero: {
    id: 'elves_hero',
    name: 'Druid Sanctum',
    faction: 'elves',
    category: 'hero',
    tier: 2,
    hp: 1200,
    goldCost: 200,
    buildTime: 25,
    width: 85,
    height: 85,
    description: 'Summons the Archdruid and awakens the Ancient Guardian champions.',
    producesUnits: ['elves_archdruid', 'elves_ancient_guardian'],
  },
  elves_tower: {
    id: 'elves_tower',
    name: 'Ancient Sentinel',
    faction: 'elves',
    category: 'tower',
    tier: 1,
    hp: 850,
    goldCost: 120,
    buildTime: 18,
    width: 60,
    height: 60,
    description: 'Living wooden turret casting silver moon darts at approaching hostiles.',
    canAttack: true,
    attackDamage: 27,
    attackRange: 190,
    attackSpeed: 1.2,
  },
};

export const TIER_UPGRADES = {
  tier_2: {
    id: 'tier_2',
    name: 'Advance to Tier 2',
    description: 'Unlocks Hero building, Tanks, Casters, and Advanced units.',
    goldCost: 250,
    researchTime: 30,
    targetTier: 2,
  },
  tier_3: {
    id: 'tier_3',
    name: 'Advance to Tier 3',
    description: 'Unlocks Siege engines, Elite units, and Tier 2 Upgrades.',
    goldCost: 350,
    researchTime: 35,
    targetTier: 3,
  },
};
