import { UnitDef } from '../types';
import { ABILITIES } from './abilities';

export const UNITS: Record<string, UnitDef> = {
  // ================= KINGDOMS =================
  kingdoms_peasant: {
    id: 'kingdoms_peasant',
    name: 'Peasant',
    faction: 'kingdoms',
    role: 'gatherer',
    tier: 1,
    hp: 180,
    attackDamage: 6,
    armor: 0,
    range: 26,
    attackSpeed: 1.3,
    moveSpeed: 70,
    goldCost: 75,
    popCost: 1,
    buildTime: 10,
    description: 'Harvests gold from mines and constructs royal kingdom structures.',
    radius: 12,
  },
  kingdoms_swordsman: {
    id: 'kingdoms_swordsman',
    name: 'Swordsman',
    faction: 'kingdoms',
    role: 'melee',
    tier: 1,
    hp: 360,
    attackDamage: 18,
    armor: 3,
    range: 28,
    attackSpeed: 1.2,
    moveSpeed: 65,
    goldCost: 120,
    popCost: 1,
    buildTime: 14,
    description: 'Disciplined infantry equipped with broadsword and sturdy heater shield.',
    radius: 14,
  },
  kingdoms_knight: {
    id: 'kingdoms_knight',
    name: 'Knight',
    faction: 'kingdoms',
    role: 'tank',
    tier: 2,
    hp: 620,
    attackDamage: 26,
    armor: 6,
    range: 30,
    attackSpeed: 1.4,
    moveSpeed: 60,
    goldCost: 220,
    popCost: 2,
    buildTime: 20,
    description: 'Armored vanguard clad in full plate, absorbing frontline punishment.',
    radius: 16,
  },
  kingdoms_archer: {
    id: 'kingdoms_archer',
    name: 'Archer',
    faction: 'kingdoms',
    role: 'ranged',
    tier: 1,
    hp: 240,
    attackDamage: 20,
    armor: 1,
    range: 160,
    attackSpeed: 1.3,
    moveSpeed: 70,
    goldCost: 135,
    popCost: 1,
    buildTime: 14,
    description: 'Sharp-eyed marksman raining arrows upon enemy forces from safety.',
    radius: 13,
  },
  kingdoms_battlemage: {
    id: 'kingdoms_battlemage',
    name: 'Battlemage',
    faction: 'kingdoms',
    role: 'caster',
    tier: 2,
    hp: 280,
    attackDamage: 22,
    armor: 1,
    range: 150,
    attackSpeed: 1.5,
    moveSpeed: 65,
    goldCost: 180,
    popCost: 2,
    buildTime: 18,
    description: 'Arcane scholar capable of unleashing destructive flame blasts.',
    radius: 13,
    abilities: [ABILITIES.battlemage_fireball],
  },
  kingdoms_priest: {
    id: 'kingdoms_priest',
    name: 'Priest',
    faction: 'kingdoms',
    role: 'support',
    tier: 2,
    hp: 250,
    attackDamage: 12,
    armor: 1,
    range: 140,
    attackSpeed: 1.6,
    moveSpeed: 65,
    goldCost: 150,
    popCost: 2,
    buildTime: 16,
    description: 'Devoted cleric who mends wounded soldiers on the battlefield.',
    radius: 13,
    abilities: [ABILITIES.priest_heal],
  },
  kingdoms_paladin: {
    id: 'kingdoms_paladin',
    name: 'Paladin',
    faction: 'kingdoms',
    role: 'hero',
    tier: 2,
    hp: 850,
    attackDamage: 36,
    armor: 5,
    range: 32,
    attackSpeed: 1.3,
    moveSpeed: 70,
    goldCost: 350,
    popCost: 3,
    buildTime: 28,
    description: 'Hero of the Realm. Wields sacred light to smite foes and heal allies.',
    radius: 18,
    abilities: [
      ABILITIES.paladin_holy_strike,
      ABILITIES.paladin_heal,
      ABILITIES.paladin_rally,
      ABILITIES.paladin_divine_shield,
    ],
  },
  kingdoms_cannon: {
    id: 'kingdoms_cannon',
    name: 'Cannon',
    faction: 'kingdoms',
    role: 'siege',
    tier: 3,
    hp: 400,
    attackDamage: 65,
    armor: 2,
    range: 240,
    attackSpeed: 2.5,
    moveSpeed: 45,
    goldCost: 280,
    popCost: 3,
    buildTime: 24,
    description: 'Heavy siege artillery designed to bombard fortifications from great distance.',
    radius: 17,
  },
  kingdoms_royal_guard: {
    id: 'kingdoms_royal_guard',
    name: 'Royal Guard',
    faction: 'kingdoms',
    role: 'elite',
    tier: 3,
    hp: 700,
    attackDamage: 38,
    armor: 7,
    range: 30,
    attackSpeed: 1.25,
    moveSpeed: 65,
    goldCost: 260,
    popCost: 2,
    buildTime: 22,
    description: 'The pinnacle of martial mastery, impenetrable armor and deadly halberd.',
    radius: 16,
  },

  // ================= HORDE =================
  horde_peon: {
    id: 'horde_peon',
    name: 'Peon',
    faction: 'horde',
    role: 'gatherer',
    tier: 1,
    hp: 190,
    attackDamage: 7,
    armor: 0,
    range: 26,
    attackSpeed: 1.3,
    moveSpeed: 70,
    goldCost: 75,
    popCost: 1,
    buildTime: 10,
    description: 'Hardy laborer who harvests gold and erects spiked war camps.',
    radius: 13,
  },
  horde_grunt: {
    id: 'horde_grunt',
    name: 'Grunt',
    faction: 'horde',
    role: 'melee',
    tier: 1,
    hp: 380,
    attackDamage: 21,
    armor: 2,
    range: 28,
    attackSpeed: 1.2,
    moveSpeed: 68,
    goldCost: 110,
    popCost: 1,
    buildTime: 13,
    description: 'Fierce frontline berserker armed with a heavy notched battleaxe.',
    radius: 15,
  },
  horde_ogre: {
    id: 'horde_ogre',
    name: 'Ogre',
    faction: 'horde',
    role: 'tank',
    tier: 2,
    hp: 720,
    attackDamage: 30,
    armor: 3,
    range: 30,
    attackSpeed: 1.5,
    moveSpeed: 60,
    goldCost: 210,
    popCost: 2,
    buildTime: 19,
    description: 'Massive hulking brute with enormous health pool and crushing blows.',
    radius: 18,
  },
  horde_troll_hunter: {
    id: 'horde_troll_hunter',
    name: 'Troll Hunter',
    faction: 'horde',
    role: 'ranged',
    tier: 1,
    hp: 250,
    attackDamage: 23,
    armor: 0,
    range: 150,
    attackSpeed: 1.2,
    moveSpeed: 72,
    goldCost: 130,
    popCost: 1,
    buildTime: 13,
    description: 'Javelin thrower with rapid piercing spear attacks.',
    radius: 13,
  },
  horde_spirit_shaman: {
    id: 'horde_spirit_shaman',
    name: 'Spirit Shaman',
    faction: 'horde',
    role: 'caster',
    tier: 2,
    hp: 290,
    attackDamage: 20,
    armor: 1,
    range: 140,
    attackSpeed: 1.5,
    moveSpeed: 65,
    goldCost: 175,
    popCost: 2,
    buildTime: 17,
    description: 'Primal spellcaster invoking ancestor spirits to bestow blood frenzy.',
    radius: 13,
    abilities: [ABILITIES.shaman_bloodsurge],
  },
  horde_wolf_rider: {
    id: 'horde_wolf_rider',
    name: 'Wolf Rider',
    faction: 'horde',
    role: 'special',
    tier: 2,
    hp: 450,
    attackDamage: 25,
    armor: 2,
    range: 32,
    attackSpeed: 1.2,
    moveSpeed: 90,
    goldCost: 190,
    popCost: 2,
    buildTime: 18,
    description: 'Swift predatory cavalry built for flanking, pursuit, and harassment.',
    radius: 16,
  },
  horde_blademaster: {
    id: 'horde_blademaster',
    name: 'Blademaster',
    faction: 'horde',
    role: 'hero',
    tier: 2,
    hp: 800,
    attackDamage: 44,
    armor: 3,
    range: 32,
    attackSpeed: 1.15,
    moveSpeed: 80,
    goldCost: 350,
    popCost: 3,
    buildTime: 28,
    description: 'Horde Hero. Peerless swordsman utilizing wind walk and deadly whirlwind.',
    radius: 17,
    abilities: [
      ABILITIES.blademaster_wind_walk,
      ABILITIES.blademaster_whirlwind,
      ABILITIES.blademaster_mirror_image,
      ABILITIES.blademaster_bladestorm,
    ],
  },
  horde_catapult: {
    id: 'horde_catapult',
    name: 'Catapult',
    faction: 'horde',
    role: 'siege',
    tier: 3,
    hp: 380,
    attackDamage: 70,
    armor: 1,
    range: 230,
    attackSpeed: 2.6,
    moveSpeed: 45,
    goldCost: 270,
    popCost: 3,
    buildTime: 23,
    description: 'Fires flaming boulders that crush structures and shatter enemy ranks.',
    radius: 17,
  },
  horde_berserker: {
    id: 'horde_berserker',
    name: 'Berserker',
    faction: 'horde',
    role: 'elite',
    tier: 3,
    hp: 640,
    attackDamage: 45,
    armor: 3,
    range: 28,
    attackSpeed: 1.1,
    moveSpeed: 75,
    goldCost: 250,
    popCost: 2,
    buildTime: 21,
    description: 'Frenzied champion dealing ferocious melee carnage.',
    radius: 16,
  },

  // ================= UNDEAD =================
  undead_acolyte: {
    id: 'undead_acolyte',
    name: 'Acolyte',
    faction: 'undead',
    role: 'gatherer',
    tier: 1,
    hp: 170,
    attackDamage: 5,
    armor: 0,
    range: 26,
    attackSpeed: 1.3,
    moveSpeed: 70,
    goldCost: 75,
    popCost: 1,
    buildTime: 10,
    description: 'Hooded cultist harvesting gold and conjuring cursed necropolis sites.',
    radius: 12,
  },
  undead_ghoul: {
    id: 'undead_ghoul',
    name: 'Ghoul',
    faction: 'undead',
    role: 'melee',
    tier: 1,
    hp: 330,
    attackDamage: 20,
    armor: 1,
    range: 26,
    attackSpeed: 1.1,
    moveSpeed: 75,
    goldCost: 105,
    popCost: 1,
    buildTime: 12,
    description: 'Ravenous undead creature with quick slashing claws.',
    radius: 13,
  },
  undead_abomination: {
    id: 'undead_abomination',
    name: 'Abomination',
    faction: 'undead',
    role: 'tank',
    tier: 2,
    hp: 680,
    attackDamage: 28,
    armor: 4,
    range: 30,
    attackSpeed: 1.45,
    moveSpeed: 58,
    goldCost: 220,
    popCost: 2,
    buildTime: 20,
    description: 'Sutured behemoth that absorbs enormous enemy fire.',
    radius: 18,
  },
  undead_crypt_archer: {
    id: 'undead_crypt_archer',
    name: 'Crypt Archer',
    faction: 'undead',
    role: 'ranged',
    tier: 1,
    hp: 230,
    attackDamage: 19,
    armor: 1,
    range: 155,
    attackSpeed: 1.3,
    moveSpeed: 70,
    goldCost: 130,
    popCost: 1,
    buildTime: 13,
    description: 'Skeletal archer firing venomous bone arrows.',
    radius: 13,
  },
  undead_necromancer: {
    id: 'undead_necromancer',
    name: 'Necromancer',
    faction: 'undead',
    role: 'caster',
    tier: 2,
    hp: 270,
    attackDamage: 18,
    armor: 1,
    range: 150,
    attackSpeed: 1.5,
    moveSpeed: 65,
    goldCost: 180,
    popCost: 2,
    buildTime: 18,
    description: 'Master of rot who summons skeleton warriors from fallen corpses.',
    radius: 13,
    abilities: [ABILITIES.necromancer_raise_skeleton],
  },
  undead_wraith: {
    id: 'undead_wraith',
    name: 'Wraith',
    faction: 'undead',
    role: 'special',
    tier: 2,
    hp: 380,
    attackDamage: 26,
    armor: 4,
    range: 120,
    attackSpeed: 1.25,
    moveSpeed: 75,
    goldCost: 190,
    popCost: 2,
    buildTime: 18,
    description: 'Incorporeal specter that drifts through attacks and chills souls.',
    radius: 14,
  },
  undead_death_knight: {
    id: 'undead_death_knight',
    name: 'Death Knight',
    faction: 'undead',
    role: 'hero',
    tier: 2,
    hp: 820,
    attackDamage: 38,
    armor: 4,
    range: 32,
    attackSpeed: 1.25,
    moveSpeed: 72,
    goldCost: 350,
    popCost: 3,
    buildTime: 28,
    description: 'Undead Hero. Wields unholy magic to siphon life and raise the dead.',
    radius: 17,
    abilities: [
      ABILITIES.death_knight_death_coil,
      ABILITIES.death_knight_raise_dead,
      ABILITIES.death_knight_death_aura,
      ABILITIES.death_knight_army_of_the_dead,
    ],
  },
  undead_bone_catapult: {
    id: 'undead_bone_catapult',
    name: 'Bone Catapult',
    faction: 'undead',
    role: 'siege',
    tier: 3,
    hp: 390,
    attackDamage: 68,
    armor: 2,
    range: 235,
    attackSpeed: 2.5,
    moveSpeed: 45,
    goldCost: 275,
    popCost: 3,
    buildTime: 23,
    description: 'Hurls cursed skulls and plague fragments to pulverize enemy bastions.',
    radius: 17,
  },
  undead_bone_dragon: {
    id: 'undead_bone_dragon',
    name: 'Bone Dragon',
    faction: 'undead',
    role: 'elite',
    tier: 3,
    hp: 680,
    attackDamage: 42,
    armor: 5,
    range: 130,
    attackSpeed: 1.3,
    moveSpeed: 65,
    goldCost: 280,
    popCost: 2,
    buildTime: 24,
    description: 'Reanimated skeletal dread wyrm exhaling freezing death upon ranks.',
    radius: 19,
  },

  // ================= ELVES =================
  elves_wisp: {
    id: 'elves_wisp',
    name: 'Wisp',
    faction: 'elves',
    role: 'gatherer',
    tier: 1,
    hp: 160,
    attackDamage: 4,
    armor: 0,
    range: 26,
    attackSpeed: 1.3,
    moveSpeed: 72,
    goldCost: 75,
    popCost: 1,
    buildTime: 10,
    description: 'Luminous nature spirit that harmonizes with gold and weaves living groves.',
    radius: 11,
  },
  elves_bladedancer: {
    id: 'elves_bladedancer',
    name: 'Bladedancer',
    faction: 'elves',
    role: 'melee',
    tier: 1,
    hp: 320,
    attackDamage: 22,
    armor: 2,
    range: 28,
    attackSpeed: 1.15,
    moveSpeed: 78,
    goldCost: 115,
    popCost: 1,
    buildTime: 13,
    description: 'Acrobatic sword master dancing through enemy skirmishes.',
    radius: 13,
  },
  elves_treant: {
    id: 'elves_treant',
    name: 'Treant',
    faction: 'elves',
    role: 'tank',
    tier: 2,
    hp: 660,
    attackDamage: 25,
    armor: 5,
    range: 30,
    attackSpeed: 1.5,
    moveSpeed: 55,
    goldCost: 230,
    popCost: 2,
    buildTime: 20,
    description: 'Living tree guardian with heavy bark armor and sweeping root strikes.',
    radius: 17,
  },
  elves_archer: {
    id: 'elves_archer',
    name: 'Elven Archer',
    faction: 'elves',
    role: 'ranged',
    tier: 1,
    hp: 220,
    attackDamage: 24,
    armor: 1,
    range: 180,
    attackSpeed: 1.25,
    moveSpeed: 75,
    goldCost: 140,
    popCost: 1,
    buildTime: 14,
    description: 'Supreme longbow marksman with unmatched firing range and agility.',
    radius: 13,
  },
  elves_sorceress: {
    id: 'elves_sorceress',
    name: 'Sorceress',
    faction: 'elves',
    role: 'caster',
    tier: 2,
    hp: 260,
    attackDamage: 21,
    armor: 1,
    range: 160,
    attackSpeed: 1.45,
    moveSpeed: 68,
    goldCost: 185,
    popCost: 2,
    buildTime: 18,
    description: 'Arcane enchantress freezing hostile movement with biting frost spells.',
    radius: 13,
    abilities: [ABILITIES.sorceress_frost_bolt],
  },
  elves_hippogriff_rider: {
    id: 'elves_hippogriff_rider',
    name: 'Hippogriff Rider',
    faction: 'elves',
    role: 'special',
    tier: 2,
    hp: 420,
    attackDamage: 28,
    armor: 2,
    range: 140,
    attackSpeed: 1.25,
    moveSpeed: 85,
    goldCost: 200,
    popCost: 2,
    buildTime: 19,
    description: 'Mobile beast rider delivering rapid projectile strikes from vantage.',
    radius: 16,
  },
  elves_archdruid: {
    id: 'elves_archdruid',
    name: 'Archdruid',
    faction: 'elves',
    role: 'hero',
    tier: 2,
    hp: 780,
    attackDamage: 35,
    armor: 3,
    range: 130,
    attackSpeed: 1.3,
    moveSpeed: 72,
    goldCost: 350,
    popCost: 3,
    buildTime: 28,
    description: 'Elven Hero. Commands lunar radiance, entangling vines, and nature restoration.',
    radius: 17,
    abilities: [
      ABILITIES.archdruid_entangle,
      ABILITIES.archdruid_moonfall,
      ABILITIES.archdruid_natures_blessing,
      ABILITIES.archdruid_wrath_of_nature,
    ],
  },
  elves_nature_catapult: {
    id: 'elves_nature_catapult',
    name: 'Nature Catapult',
    faction: 'elves',
    role: 'siege',
    tier: 3,
    hp: 370,
    attackDamage: 66,
    armor: 2,
    range: 240,
    attackSpeed: 2.5,
    moveSpeed: 48,
    goldCost: 270,
    popCost: 3,
    buildTime: 23,
    description: 'Launches enchanted glaive spheres that shatter defensive walls.',
    radius: 17,
  },
  elves_ancient_guardian: {
    id: 'elves_ancient_guardian',
    name: 'Ancient Guardian',
    faction: 'elves',
    role: 'elite',
    tier: 3,
    hp: 660,
    attackDamage: 40,
    armor: 6,
    range: 32,
    attackSpeed: 1.2,
    moveSpeed: 65,
    goldCost: 270,
    popCost: 2,
    buildTime: 23,
    description: 'Sacred grove champion infused with eternal starlight and ironwood.',
    radius: 18,
  },

  // ================= TEMPORARY SUMMONS =================
  summon_skeleton: {
    id: 'summon_skeleton',
    name: 'Skeleton Warrior',
    faction: 'undead',
    role: 'summon',
    tier: 1,
    hp: 190,
    attackDamage: 15,
    armor: 1,
    range: 26,
    attackSpeed: 1.2,
    moveSpeed: 68,
    goldCost: 0,
    popCost: 0,
    buildTime: 0,
    description: 'Temporary reanimated warrior raised from a battlefield corpse.',
    radius: 12,
  },
  summon_frenzied_ghoul: {
    id: 'summon_frenzied_ghoul',
    name: 'Frenzied Ghoul',
    faction: 'undead',
    role: 'summon',
    tier: 2,
    hp: 250,
    attackDamage: 24,
    armor: 2,
    range: 26,
    attackSpeed: 1.0,
    moveSpeed: 78,
    goldCost: 0,
    popCost: 0,
    buildTime: 0,
    description: 'Summoned by Army of the Dead.',
    radius: 13,
  },
  summon_ancient_treant: {
    id: 'summon_ancient_treant',
    name: 'Ancient Treant Protector',
    faction: 'elves',
    role: 'summon',
    tier: 2,
    hp: 480,
    attackDamage: 32,
    armor: 5,
    range: 30,
    attackSpeed: 1.4,
    moveSpeed: 55,
    goldCost: 0,
    popCost: 0,
    buildTime: 0,
    description: 'Summoned by Wrath of Nature.',
    radius: 18,
  },
  summon_mirror_image: {
    id: 'summon_mirror_image',
    name: 'Mirror Image',
    faction: 'horde',
    role: 'summon',
    tier: 2,
    hp: 400,
    attackDamage: 12,
    armor: 1,
    range: 30,
    attackSpeed: 1.15,
    moveSpeed: 80,
    goldCost: 0,
    popCost: 0,
    buildTime: 0,
    description: 'Spectral illusion mimicking the Blademaster.',
    radius: 16,
  },
};
