import { UpgradeDef } from '../types';

export const UPGRADES: Record<string, UpgradeDef> = {
  weapons_1: {
    id: 'weapons_1',
    name: 'Iron Forging I',
    category: 'weapons',
    level: 1,
    tierRequired: 1,
    goldCost: 150,
    researchTime: 20,
    description: 'Improves weapons, increasing all friendly military unit attack damage by +10%.',
    bonus: 0.10,
  },
  weapons_2: {
    id: 'weapons_2',
    name: 'Steel Forging II',
    category: 'weapons',
    level: 2,
    tierRequired: 2,
    goldCost: 250,
    researchTime: 30,
    description: 'Masterwork forging, increasing attack damage by an additional +10% (total +20%).',
    bonus: 0.20,
  },
  armor_1: {
    id: 'armor_1',
    name: 'Reinforced Mail I',
    category: 'armor',
    level: 1,
    tierRequired: 1,
    goldCost: 150,
    researchTime: 20,
    description: 'Thickens unit armor plating, adding +1 to all unit armor values.',
    bonus: 1,
  },
  armor_2: {
    id: 'armor_2',
    name: 'Dragonscale Plate II',
    category: 'armor',
    level: 2,
    tierRequired: 2,
    goldCost: 250,
    researchTime: 30,
    description: 'Impenetrable reinforcement, adding another +1 armor (total +2 armor).',
    bonus: 2,
  },
  training_1: {
    id: 'training_1',
    name: 'Endurance Drills I',
    category: 'training',
    level: 1,
    tierRequired: 1,
    goldCost: 150,
    researchTime: 20,
    description: 'Rigorous conditioning, increasing all unit maximum HP by +10%.',
    bonus: 0.10,
  },
  training_2: {
    id: 'training_2',
    name: 'Veteran Discipline II',
    category: 'training',
    level: 2,
    tierRequired: 2,
    goldCost: 250,
    researchTime: 30,
    description: 'Legendary toughness, increasing unit maximum HP by an additional +10% (total +20%).',
    bonus: 0.20,
  },
};
